### ISSUE TITLE
Make xlabel customizable

### ISSUE THREAD

**Issue by vfdev-5** [stared/livelossplot#115]
## 🚀 Feature

Some time we would like to log values per iteration during the training and other values per epoch (e.g. after evaluating a model). It would be nice to have a possibility to customize x axis according to "type" of logging: per iteration or per epoch or whatever...

Currently, it seems like to be hard-coded and can not be simply modified:
https://github.com/stared/livelossplot/blob/a7e30dd121425871500444ef06964e7b4b16057c/livelossplot/outputs/matplotlib_plot.py#L69

@stared @Bartolo1024 what do you, guys, think ?

**Comment by Bartolo1024** [comment]
@stared maybe we should add some metadata to metrics / groups - to notify plugins about metric-wise properties like step units?

**Comment by stared** [comment]
@vfdev-5 So, in general, I want to make plots more customizable.

I kind of procrastinate on that because there are a few possibilities:

* custom name for x-label
* custom function for plot labels, annotations, anything (so e.g. people can change also legend)
* whole custom function for a plot (the most general)

And on top of that, there is a long-overdue idea of switching to object-oriented API #16.

I like the idea of @Bartolo1024 to attach the x-label to groups (as plots are per group) - so one can combine per-batch and per-epoch plots.

**Comment by vfdev-5** [comment]
Either solution works for as far as it show correct plots with right axes :)

**Comment by stared** [comment]
With `0.5.2` it is customizable, vide <https://github.com/stared/livelossplot/blob/master/examples/matplotlib.ipynb>, thanks to @Bartolo1024.
